NetCore-Training/ASP NET diffs MB/WebApplicationsNet/WebApplication1/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class DemoController : Controller
    {
        public ActionResult PostData()
        {
            return View(viewName: "Formulario");
        }
        // GET: Demo/Index
        public ActionResult Index(int id, Shared.Dtos.User user, Shared.DTOs.Product products)
        { 
            ViewBag.Title = "Index Page";

            return View();
        }
    }
}

NetCore-Training/ASP NET diffs MB/WebApplicationsNet/WebApplication1/Views/Demo/Formulario.cshtml
@{
    ViewBag.Title = "Formulario";
}

<h2>Favor de proporcionar los datos solicitados</h2>

@using (Html.BeginForm("Index", "Demo"))
{
    <p>
        <label>Id Producto</label>
        <input type="text" id="productsId" name="products.Id" placeholder="Introducir tu id producto" />
    </p>
    <p>
        <label>Id</label>
        <input type="text" id="Id" name="Id" placeholder="Introducir tu id" />
    </p>
    <p>
        <label>Nombre Usuario</label>
        <input type="text" id="userName" name="user.Name" placeholder="Introducir tu nombre de usuario" />
    </p>
    <p>
        <label>Nombre Producto</label>
        <input type="text" id="productsName" name="products.Name" placeholder="Introducir tu nombre de producto" />
    </p>
    <p>
        <label>Id Proveedor</label>
        <input type="text" id="productsVendorId" name="products.VendorId" placeholder="Introducir el id de proveedor" />
    </p>
    <input type="submit" value="Enviar info" />
    <input id="btnEnviarInfo" type="button" value="Enviar info (con ajax)"/>
}

@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function () {
            $('#btnEnviarInfo').click(function () {
                $.ajax({
                    url: '/Demo/Index/3012',
                    method: 'post',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({
                        'user': {
                            'name': $('#userName').val()
                        },
                        'products': {
                            'name': $('#productsName').val(),
                            'vendorid': $('#productsVendorId').val(),
                            'id': $('#productsId').val(),
                        },
                        'id': '300'
                    }),
                    success: function () {
                        alert('Petición recibida y procesada exitosamente');
                    },
                    error: function () {
                        alert('Petición erronea');
                    }
                });
            });
        });
    </script>
    }

NetCore-Training/ASP NET diffs MB/WebApplicationsNet/WebApplication1/Views/Demo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index (Demo controller)</h2>

NetCore-Training/ASP NET diffs MB/WebApplicationsNet/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("scripts", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>